--------------------------------------------------------
--  File created - Friday-July-15-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPORDERS
--------------------------------------------------------

  CREATE TABLE "ORA1"."SPORDERS" 
   (	"ORDERID" NUMBER, 
	"PRODUCTID" NUMBER, 
	"USERID" NUMBER, 
	"QUANTITY" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SPORDERS_PK" ON "ORA1"."SPORDERS" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SPORDERS
--------------------------------------------------------

  ALTER TABLE "ORA1"."SPORDERS" ADD CONSTRAINT "SPORDERS_PK" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."SPORDERS" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SPORDERS
--------------------------------------------------------

  ALTER TABLE "ORA1"."SPORDERS" ADD CONSTRAINT "SPORDERS_FK1" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "ORA1"."SPPRODUCTS" ("PRODUCTID") ENABLE;
  ALTER TABLE "ORA1"."SPORDERS" ADD CONSTRAINT "SPORDERS_FK2" FOREIGN KEY ("USERID")
	  REFERENCES "ORA1"."SPUSERS" ("USERID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger SPORDERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."SPORDERS_TRG" 
BEFORE INSERT ON SPORDERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDERID IS NULL THEN
      SELECT SPORDERS_SEQ.NEXTVAL INTO :NEW.ORDERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."SPORDERS_TRG" ENABLE;
