--------------------------------------------------------
--  File created - Friday-July-15-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SPUSERS
--------------------------------------------------------

  CREATE TABLE "ORA1"."SPUSERS" 
   (	"USERID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"USEREMAIL" VARCHAR2(50 BYTE), 
	"HASHEDPASSWORD" VARCHAR2(100 BYTE), 
	"SALT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPUSERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SPUSERS_PK" ON "ORA1"."SPUSERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SPUSERS
--------------------------------------------------------

  ALTER TABLE "ORA1"."SPUSERS" ADD CONSTRAINT "SPUSERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."SPUSERS" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger SPUSERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."SPUSERS_TRG" 
BEFORE INSERT ON SPUSERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USERID IS NULL THEN
      SELECT SPUSERS_SEQ.NEXTVAL INTO :NEW.USERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."SPUSERS_TRG" ENABLE;
